from distutils.core import setup
setup(name='django-simple-export',
      version='0.1',
      license='BSD',
      packages=['simple_export'],
      include_package_data=True,
      description='Simple import / export utility for Django with large data support.  Compatible with Mongoengine.',
      author='Mark Skelton',
      author_email='mark@software13.co.uk',
      url='https://github.com/mtskelton/django-simple-export/',
      install_requires=['django>=1.7', 'metamagic.json'],
      requires=[],
      data_files=['LICENSE', 'README.md'],
      provides=['simple_export'],
      py_modules=['simple_export.management.commands.simple_export', 'simple_export.management.commands.simple_import'],
      classifiers=['Development Status :: 2 - Pre-Alpha',
                   'Intended Audience :: Developers',
                   'Framework :: Django',
                   'Environment :: Web Environment',
                   'Programming Language :: Python',
                   'Programming Language :: Python :: 3',
                   'Programming Language :: Python :: 3.4',
                   'License :: OSI Approved :: MIT License',
                   'Topic :: Software Development :: Libraries :: Python Modules',
                   ]
      )
